                                   [package]
name = "pallet-scheduler"
version = "29.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME Scheduler pallet"
readme = "README.md"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame = { workspace = true, features = ["experimental", "runtime"] }
docify = { workspace = true }

[dev-dependencies]
pallet-preimage = { workspace = true, default-features = true }
substrate-test-utils = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
std = [
	"codec/std",
	"frame/std"
	"log/std",
	"pallet-preimage/std",
	"scale-info/std",
]
try-runtime = [
	"frame/try-runtime"
	"pallet-preimage/try-runtime",
]
