[package]
name = "pallet-paged-list-fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Fuzz storage types of pallet-paged-list"
publish = false

[lints]
workspace = true

[[bin]]
name = "pallet-paged-list-fuzzer"
path = "src/paged_list.rs"

[dependencies]
arbitrary = { workspace = true }
honggfuzz = { workspace = true }

frame = { workspace = true, features = ["experimental", "runtime"] }
pallet-paged-list = { features = ["std"], workspace = true }
